### ISSUE TITLE
Missing constraints on dependencies?

### ISSUE THREAD

**Issue by srenatus** [ltext/ltext#10]
Hi there.

Trying to build ltext locally, I noticed that `mtl` is needed in the latest version, [2.2.1](https://hackage.haskell.org/package/mtl-2.2.1), for the [`Control.Monad.Except` re-export](https://hackage.haskell.org/package/mtl-2.2.1/changelog).

ltext looks quite nice, thanks.

Btw, the cabal file [still points at your @athanclark github repo](https://github.com/ltext/ltext/blob/master/ltext.cabal#L76).

**Comment by dbushenko** [comment]
Also you may add 'mtl-compat' -- it helped building it with older 'mtl'.

Cool project! Thanks!
