### ISSUE TITLE
Unexpected Behavoir

### ISSUE THREAD

**Issue by alcarney** [ltext/ltext#14]
I am trying to use `ltext` to help me parameterise a number of shell scripts where I have to experiment with a bunch of values and options. However when I try to do this I seem to run into a number of issues:
- If `$$ value %%` is preceded by text then no substitution occurs
- If text follows `$$ value %%`, then on substitution the text is removed 

Below are a few example cases:

**Preceding text**

The template file:

```
$ cat template

$$ value %%

This is broken

Nothing happens in this case $$ value %%
```

The file to be substituted

```
$ cat values

I am a value

```

Which when applied using `ltext` I get the following output

```
$ ltext "template values" --left "$$" --right "%%"

This is broken

Nothing happens in this case $$ value %%

```

**Text following the parameter**

The template file

```
$ cat template

$$ value %%

This is broken

$$ value %% now you see me
```

The file to be substitued

```
$ cat values

now you don't
```

When applied using `ltext` I get the following

```
$ ltext "template values" --left "$$" --right "%%"

This is broken

now you don't
```

I'm not sure if I'm missing something obvious or that that I should be doing someting different, but any help would be greatly appreciated

**Comment by athanclark** [comment]
I agree, this is a very disappointing bug. I'm working on a large revamp of the system right now - which will take care of this bug.

Right now, ltext only supports line-by-line substitutions, but in the new one, we'll have character-by-character, which will fix this issue. I'll ping this thread as soon as the new release is out.

**Comment by Prillan** [comment]
This issue seems to be present in the latest version. Is there a reason it was closed?
